spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: univan
    password: univan
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect